<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - Selenium - TestNG - FireFox on Windows</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>Selenium - TestNG - FireFox on Windows</h1>
<p>
  Test duration: 236.914s
</p>



  <table class="resultsTable">
    <tr><th colspan="4" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="4" class="group">rakuten.PointClubVerification</td>
      </tr>
            
<tr>

  <td class="method">
    <a href="javascript:void(0)" onclick="clickHandler(this);" title="Click to expand/collapse">
                  <span class="description" title="Open My Account">TC_Point_Club_Verification</span>
         </a>
  </td>
  
  <td class="TMDes">Open My Account</td>

  <td class="duration">
    236.423s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">"http://www.rakuten.com.my", "test.rakuten25@gmail.com", "rakuten01"</span><br />
            


        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.Throwable: Mulitple failures (4):<br/>
Failure 1 of 4<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertTrue(Assert.java:42)<br/>
	at org.testng.Assert.assertTrue(Assert.java:52)<br/>
	at com.logigear.selenium.QTiumAssert.verifyTrue(QTiumAssert.java:13)<br/>
	at com.logigear.selenium.QTiumAssert.verifyTrue(QTiumAssert.java:26)<br/>
	at rakuten.PointClubPageAction.VerifyPageUI(PointClubPageAction.java:17)<br/>
	at rakuten.PointClubVerification.TC_Point_Club_Verification(PointClubVerification.java:46)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br/>
	at java.lang.reflect.Method.invoke(Unknown Source)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br/>
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br/>
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
<br/>
Failure 2 of 4<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertTrue(Assert.java:42)<br/>
	at org.testng.Assert.assertTrue(Assert.java:52)<br/>
	at com.logigear.selenium.QTiumAssert.verifyTrue(QTiumAssert.java:13)<br/>
	at com.logigear.selenium.QTiumAssert.verifyTrue(QTiumAssert.java:26)<br/>
	at rakuten.PointClubPageAction.VerifyPageUI(PointClubPageAction.java:18)<br/>
	at rakuten.PointClubVerification.TC_Point_Club_Verification(PointClubVerification.java:46)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br/>
	at java.lang.reflect.Method.invoke(Unknown Source)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br/>
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br/>
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
<br/>
Failure 3 of 4<br/>
java.lang.AssertionError: expected [true] but found [false]<br/>
	at org.testng.Assert.fail(Assert.java:94)<br/>
	at org.testng.Assert.failNotEquals(Assert.java:494)<br/>
	at org.testng.Assert.assertTrue(Assert.java:42)<br/>
	at org.testng.Assert.assertTrue(Assert.java:52)<br/>
	at com.logigear.selenium.QTiumAssert.verifyTrue(QTiumAssert.java:13)<br/>
	at com.logigear.selenium.QTiumAssert.verifyTrue(QTiumAssert.java:26)<br/>
	at rakuten.PointClubPageAction.VerifyPageUI(PointClubPageAction.java:19)<br/>
	at rakuten.PointClubVerification.TC_Point_Club_Verification(PointClubVerification.java:46)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br/>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br/>
	at java.lang.reflect.Method.invoke(Unknown Source)<br/>
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br/>
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br/>
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br/>
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br/>
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br/>
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br/>
	at org.testng.TestRunner.privateRun(TestRunner.java:767)<br/>
	at org.testng.TestRunner.run(TestRunner.java:617)<br/>
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br/>
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br/>
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br/>
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br/>
	at java.util.concurrent.FutureTask.run(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br/>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br/>
	at java.lang.Thread.run(Unknown Source)<br/>
<br/>
Failure 4 of 4<br/>
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)<br/>
Command duration or timeout: 110 milliseconds<br/>
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html<br/>
Build info: version: &apos;2.45.0&apos;, revision: &apos;32a636c&apos;, time: &apos;2015-03-05 22:01:35&apos;<br/>
System info: host: &apos;lgvn14663&apos;, ip: &apos;192.168.171.42&apos;, os.name: &apos;Windows 7&apos;, os.arch: &apos;x86&apos;, os.version: &apos;6.1&apos;, java.version: &apos;1.8.0_20&apos;<br/>
Driver info: io.appium.java_client.android.AndroidDriver<br/>
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=, platform=ANDROID, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]<br/>
Session ID: 187c0b5e1ac647f5fc19e7e304bd2887<br/>
*** Element info: {Using=xpath, value=//h1[@class=&apos;b-ttl-1&apos;]}</b></a><br />
    <div class="stackTrace" id="exception-0">
              sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)<br />
              sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)<br />
              java.lang.reflect.Constructor.newInstance(Unknown Source)<br />
              org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)<br />
              org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)<br />
              org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)<br />
              io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)<br />
              org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)<br />
              org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)<br />
              org.openqa.selenium.By$ByXPath.findElement(By.java:357)<br />
              org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)<br />
              com.logigear.selenium.QTiumAutomation.findElement(QTiumAutomation.java:240)<br />
              com.logigear.selenium.QTiumAutomation.getText(QTiumAutomation.java:314)<br />
              com.logigear.selenium.QTiumAutomation.getText(QTiumAutomation.java:310)<br />
              rakuten.PointClubPageAction.VerifyLanguage(PointClubPageAction.java:27)<br />
              rakuten.PointClubVerification.TC_Point_Club_Verification(PointClubVerification.java:47)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.access$000(SuiteRunner.java:37)<br />
              org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)<br />
              org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)<br />
              java.util.concurrent.FutureTask.run(Unknown Source)<br />
              java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)<br />
              java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)<br />
              java.lang.Thread.run(Unknown Source)<br />
                </div>
      </td>
</tr>
      </table>


  
</body>
</html>
